makers=['acura',
'alfa romeo',
'aston martin',
'audi',
'bentley',
'bmw',
'buick',
'cadillac',
'chevrolet',
'chrysler',
'datsun',
'dodge',
'ferrari',
'fiat',
'ford',
'geely',
'general motors',
'geo',
'gmc',
'harley',
'honda',
'hummer',
'hyundai',
'infiniti',
'isuzu',
'jaguar',
'jeep',
'kawasaki',
'kia',
'ktm',
'laforza',
'lamborghini',
'lancia',
'land rover',
'lexus',
'lincoln',
'lotus',
'maserati',
'mazda',
'mercedes-benz',
'mercury',
'mini',
'mitsubishi',
'nissan',
'oldsmobile',
'peugeot',
'pontiac',
'porsche',
'plymouth',
'renault',
'rolls-royce',
'saab',
'saturn',
'scion',
'subaru',
'suzuki',
'tesla',
'toyota',
'volkswagen',
'volvo',
'vespa',
'yamaha']

make_corrected = {
    'olds': 'oldsmobile',
    'toyo': 'toyota',
    'vw' : 'volkswagen',
    'volkswagon' : 'volkswagen',
    'infinity' : 'infiniti',
    'toyt' : 'toyota',
    'huyundai': 'hyundai',
    'accura' : 'acura',
    'volks' : 'volkswagen',
    'chev' : 'chevrolet',
    'chevy' : 'chevrolet',
    'gm' : 'general motors',
    'mercedes' : 'mercedes-benz',
    'benz' : 'mercedes-benz',
    'landrover' : 'land rover',
    'hyuandi' : 'hyundai',
    'cadilac': 'cadillac',
    'chrys' : 'chrysler',
    'minicooper' : 'mini'}